language: python
install:
- pip install mkdocs mkdocs-material
script:
- mkdocs build --verbose --clean --strict
deploy:
 provider: pages
 repo: aed-frre/aed-frre.github.io 
 target_branch: master
 skip_cleanup: true
 github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
 local_dir: site
 on:
   branch: master
