site_name: Guía de Trabajos Prácticos
nav:
  - index.md
  - Práctica: 
    - 0. Algortimos: practica/0.md
    - 1. Elementales: 
      - 1.1. Datos y Estructuras: practica/1.1.md
      - 1.2. Subacciones: practica/1.2.md
    - 2. Secuencias y Archivos Indexados:
      - 2.1. Secuencias de datos elementales: practica/2.1.md
      - 2.2. Secuencias de datos elementales extra: practica/2.21.md
      - 2.3. Archivos Secuenciales: practica/2.2.md
      - 2.4. Archivos Indexados: practica/2.3.md
    - 3. Arreglos: practica/3.md
    - 4. Listas: practica/4.md
    - 5. Recursividad: practica/5.md
    - X. Parcial: practica/x.md
  - Complementos Teóricos:
    - Mezcla: teoria/mezcla.md
    - Corte de Control: teoria/corte.md
    - Actualización: teoria/actualizacion.md
    - Arreglos: teoria/arreglos.md
    - Listas: teoria/listas.md
  - Complementarios:
    - 1. Datos y Estructuras Elementales: complementarios/1.md
    - 2. Tratamiento de Secuencias:
      - 2.1. Secuencias de datos elementales: complementarios/2.1.md
      - 2.2. Archivos Secuenciales: complementarios/2.2.md
    - 3. Tratamiento de Arreglos: complementarios/3.md
    - 4. Tratamiento de Listas: complementarios/4.md
theme:
  name: 'material'
  language: 'es'
  custom_dir: custom/
  palette:
    primary: 'blue grey'
    accent: 'indigo'
  features:
    - tabs
    - instant
markdown_extensions:
- toc:
    permalink: true
extra_css:
  - 'extra/css/extra.css'
extra_javascript:
  - 'extra/js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
extra:
  analytics:
    provider: google
    property: UA-140521258-1
  social:
    - icon: fontawesome/brands/github-alt
      link: 'https://github.com/aed-frre/site'
