name: Build and Deploy Page
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: pip install mkdocs-material==8.5.10
      - name: Build Pages
        run: mkdocs build --verbose --clean --strict
      - name: Save commit info
        run: echo "${{ github.repository }}@${{ github.sha }}" >> site/commits
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v3
        with:
          repository: aed-frre/aed-frre.github.io
          path: pages
          token: ${{ secrets.TOKEN }}
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: site
      - name: Set Commit ENV
        run: echo "COMMIT_MESSAGE=$(tail -n 1 commits)" >> $GITHUB_ENV
        id: commit
      - name: Push
        run: |
         git config --global user.name "GitHub Action Bot"
         git config --global user.email "<>"
         git add --all
         git commit -m "${{ env.COMMIT_MESSAGE }}"
         git push
