name: Build and Deploy Page
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3
        with:
          path: source 
      - name: Checkout GitHub Pages repository
        uses: actions/checkout@v3
        with:
          repository: aed-frre/aed-frre.github.io
          path: pages
          token: ${{ secrets.TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Dependencies
        run: pip install mkdocs-material==8.5.10
      - name: Build Pages
        run: mkdocs build --verbose --clean --strict
        working-directory: source
      - run: cp -rf source/site pages
